### PR TITLE
This fixes the docker sha256 mismatch for docker 1.5.0

### PR DESCRIPTION
**Pull request by seryl**
Should alleviate the mismatches for docker 1.5.0; likely to effect 1.4.0 as well.

### CODE REVIEW

**Comment by seryl** [comment]
Golang: 1.4.1
Docker: 1.5.0

**Comment by edanaher** [comment]
But this will presumably break earlier versions?

**Comment by seryl** [comment]
Have not tested it. I'll look at it this evening.

Josh Toft
(650) 282-0070

**Comment by edanaher** [comment]
We're upgrading to Docker 1.5, and things seem to be working fine so far (modulo the lack of HTTPS, which is easy enough to work around).

What "mismatches" are you seeing that this fixes?

**Comment by irabinovitch** [comment]
@seryl  ping?

**Comment by seryl** [comment]
Seems to behave this way on every centos node I've played with, versions back to 1.2.0 up to 1.6.2.

We can change this so that it will only add the newline if it's missing, it appears to be only occurring on centos builds.

```go
if jsonContent[len(jsonContent)-1] != '\n' {
  sha256Writer.Write([]byte("\n"))
}
```

**Pull request closed without merging**
